### ISSUE TITLE
Once ChatGPT has been tagged in a thread, it will automatically reply to any reply.... this is very annoying. It should only reply when it is tagged in the latest reply of a thread.

### ISSUE THREAD

**Issue by OlivierVernin** [yGuy/chatgpt-mattermost-bot#42]
See the attached screenshot, as soon as i mentioned `@chatgpt` once as a string (not even a tag) on the red cross. he started to pollute my conversation with my team. This is especially annoying as my team would like to discuss the response from ChatGPT in the same thread. For us, ChatGPT should only been triggered on the reply where he is explicitly mentioned. 

Would there be a way to have different mode of  triggering chatGPT sometimes in full interactive mode (as now) and sometime in a more on-demand way. This is especially true for ChatGPT4 with an API limit of 24 requests per 3hours, you don't want to trigger him at every reply. Still when summoned on-demand ChatGPT should be able to use all the previous messages of the thread.

![Capture d’écran 2023-06-13 à 19 42 12](https://github.com/yGuy/chatgpt-mattermost-bot/assets/19687203/ec250857-6231-4c5a-9580-463355e68875)

**Comment by yGuy** [comment]
ChatGPT is lying, here, obviously. 

There is somewhat of a (very quiet) discussion over here: https://github.com/yGuy/chatgpt-mattermost-bot/pull/15
I am not sure about the usability, for those cases where you do want do have a dialog with chatgpt, I think it is pretty annoying to always tag it in every sentence. You don't do it in you example, either. I would love to see this discussed and see different alternatives. I know, the current situation can be annoying. You need to start a new thread in order to "stop" chatgpt from listening. We might come up with a stop-word approach. I don't like it having to @-tag it in each and every reply.

How would you like to see it implemented? Have you tried the version in the pull-request?

**Comment by OlivierVernin** [comment]
Hi, thank you for your quick response.

No, we are using the main branch version. What is different with the PR version?

Being able to stop ChatGpt on a thread seems a good compromise. As a stop word: "chatgpt stop".

The thing is that

**Comment by yGuy** [comment]
Regarding the differences, just look at the PR and the discussion.

Regarding your second idea and question: See also https://github.com/yGuy/chatgpt-mattermost-bot/issues/28

**Comment by yGuy** [comment]
With the 2.0 release, you can silence the bot and later make it respond, again.
Can you test the version and provide feedback? That would be awesome.
