### ISSUE TITLE
GPT-4 API

### ISSUE THREAD

**Issue by alejandroed** [yGuy/chatgpt-mattermost-bot#7]
Hello!

Is there any way to set the new GPT-4 api instead of 3.5?

BR

**Comment by yGuy** [comment]
GPT-4 has not yet been fully released. I don't have access to it. If you can help me get access to it, I should be able to test it.
See https://platform.openai.com/docs/models/gpt-4

That said, I guess you can simply change the model identifier in this line: https://github.com/yGuy/chatgpt-mattermost-bot/blob/c6420ef6680604ac3ed6033b231fb8266482ef66/src/openai-thread-completion.js#L9

Note that GPT-4 is significantly slower (at least in the chat UI) and since the MM Bot does not stream the answer but only shows it upon completion, it may feel like it takes too long to answer. In my experience model 4 is about 3x to 10x slower to answer and the quality improvements aren't worth it for a simple chat system, likely.

**Comment by yGuy** [comment]
I just tried it and it *seems* to work. I cannot be perfectly sure, because I actually asked the model and it told me there is no GPT-4. Which was probably correct at the time it was trained:

>yguy: Hey @chatgpt - are you there?

>chatgpt: Hello! Yes, I'm here. How can I assist you today?

>yguy:Can you tell me what version you are running your language model on? 

>chatgpt: I am running on OpenAI's GPT-3.5-turbo, the latest version of the language model. If you have any questions or need assistance, feel free to ask.

>yguy: Are you sure this isn't GTP-4?

>chatgpt: Yes, I'm sure. As of my current knowledge, I am running on GPT-3.5-turbo, which is the latest version available. GPT-4 has not been released by OpenAI at this moment.

It could also be that while the API call succeeded it's still using GPT-3.5-turbo internally. I don't know how to test this and be sure...
Anyway I added the option with the 1.3.0 release to specify the model and it seems to work.

**Comment by alejandroed** [comment]
Same behaviour here, thanks for the 1.3.0 update.
